# Generated by Django 5.2.8 on 2025-11-15 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='location',
        ),
        migrations.RemoveField(
            model_name='college',
            name='name',
        ),
        migrations.AddField(
            model_name='college',
            name='college_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='college',
            name='college_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='college',
            name='college_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='college_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='college',
            name='college_photo',
            field=models.ImageField(blank=True, null=True, upload_to='college_photos/'),
        ),
        migrations.AddField(
            model_name='college',
            name='estab_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enroll_no', models.CharField(max_length=100, unique=True)),
                ('dob', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.college')),
            ],
            options={
                'unique_together': {('college', 'enroll_no')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=100, unique=True)),
                ('document_name', models.CharField(max_length=255)),
                ('issued_by', models.CharField(max_length=255)),
                ('issued_to', models.CharField(max_length=255)),
                ('issued_date', models.DateField()),
                ('file', models.FileField(upload_to='documents/')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.college')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.student')),
            ],
            options={
                'unique_together': {('student', 'document_name')},
            },
        ),
    ]
