# Generated by Django 5.2.8 on 2025-11-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_college_user_alter_college_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='Advimage',
            field=models.ImageField(blank=True, null=True, upload_to='advantages/'),
        ),
        migrations.AddField(
            model_name='college',
            name='Advtext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='Aimage1',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/'),
        ),
        migrations.AddField(
            model_name='college',
            name='Aimage2',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/'),
        ),
        migrations.AddField(
            model_name='college',
            name='Aimage3',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/'),
        ),
        migrations.AddField(
            model_name='college',
            name='Atext1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='Atext2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='Atext3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='awardtext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='bgimage',
            field=models.ImageField(blank=True, null=True, upload_to='college_bg/'),
        ),
        migrations.AddField(
            model_name='college',
            name='contact1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='contact2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='contact3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='p_detail1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='p_detail2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
