# Generated by Django 5.2.8 on 2025-11-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_college_advimage_college_advtext_college_aimage1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='B.Tech'),
        ),
    ]
