# Generated by Django 5.2.8 on 2025-11-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Uploaded', 'Uploaded'), ('Issued', 'Issued')], default='Uploaded', max_length=50),
        ),
    ]
