# Generated by Django 5.2.8 on 2025-11-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_no',
            field=models.CharField(default='SIET000000016', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Uploaded', 'Uploaded'), ('Issued', 'Issued'), ('Verified', 'Verified'), ('Pending', 'Pending'), ('Fake', 'Fake')], default='pending', max_length=50),
        ),
    ]
