# Generated by Django 5.2.8 on 2025-11-30 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_document_doc_no_alter_document_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='document',
            name='issued_by_college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to='app.college'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Uploaded', 'Uploaded'), ('Verified', 'Verified'), ('Pending', 'Pending'), ('Fake', 'Fake')], default='Uploaded', max_length=20),
        ),
        migrations.RemoveField(
            model_name='document',
            name='issued_by',
        ),
    ]
