# Generated by Django 5.2.8 on 2025-12-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_document_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Uploaded', 'Uploaded'), ('Verified', 'Verified'), ('Pending', 'Pending'), ('Fake', 'Fake'), ('Issued', 'Issued')], default='Uploaded', max_length=20),
        ),
    ]
