# Generated by Django 5.2.8 on 2025-12-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_id',
            field=models.CharField(max_length=100),
        ),
    ]
